# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftyJSONMappable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON', '~>3.1.4'
	pod 'Moya/RxSwift', '~>8.0.4'
  # Pods for SwiftyJSONMappable

  target 'SwiftyJSONMappableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyJSONMappableUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
